name: Deploy Development

on:
  workflow_dispatch:

concurrency:
  group: deploy-dev
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: development
      app_env: development
    secrets: inherit
