name: Deploy Staging

on:
  push:
    branches: [main]

concurrency:
  group: deploy-stg
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: paseo
      app_env: staging
    secrets: inherit
