name: Deploy Development
on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Deploy target'
        required: true
        type: choice
        options:
          - westend.li
          - dotli.dev
          - paseoli.dev
          - testnet.li

concurrency:
  group: deploy-dev-${{ github.event.inputs.target }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: >-
        ${{
          github.event.inputs.target == 'westend.li' && 'development'
          || github.event.inputs.target == 'paseoli.dev' && 'dev-paseo'
          || github.event.inputs.target == 'testnet.li' && 'dev-test'
          || 'dev-polkadot'
        }}
      app_env: development
    secrets: inherit
